language: ruby
rvm:
  - 2.2.5
sudo: false
script:
  - bundle exec jekyll build -d _site
  # - bundle exec htmlproofer ./_site --only-4xx --check-html --allow-hash-href --disable-external
after_success:
  # - bash gh-pages.sh
