markdown: kramdown
highlighter: rouge

url: "https://mathewmariani.com"
baseurl:

plugins:
  - kramdown
  - rouge
  - jekyll-sitemap

permalink: pretty

exclude:
  - "node_modules"
  - "gulpfile.js"
  - "package.json"
  - "vendor"

# metadata
meta:
  author: "Mathew Mariani"
  title: "Mathew Mariani"
  desc: "I enjoy programming end-user software; working on solving new problems, and learning new skills.\nWith a passion for graphics programming and embedded languages."
  # desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
  generator: "Jekyll"
  type: "website"
  url: "https://mathewmariani.com"
  image: "https://mathewmariani.com/assets/img/mariani_mat.jpg"
  keywords: "mathew mariani"

# info
info:
  name: "Mathew Mariani"
  desc: "I enjoy programming end-user software; working on solving new problems, and learning new skills.\nWith a passion for graphics programming and embedded languages."
  location: "Montreal, Canada"

social:
  github: https://github.com/mathewmariani
  twitter: https://twitter.com/mattymariani
  email: mailto:mat.mariani@hotmail.com

games:
  name: "Games"
  desc: "Some games I've made using technologies such as Love2D, and Unity3D."

programming:
  name: "Programming"
  desc: "Small general stuff I've programmed over time."

graphics:
  name: "Graphics"
  desc: "Some graphical programming using Love2d, OpenGL, and Unity3D."

extensions:
  name: "Extensions"
  desc: "Packages for the hackable text editor Atom."

blog:
  name: "Posts"
  desc: "Small posts I've written to help expand my understanding for topics."
