markdown: kramdown
highlighter: rouge

url: "https://mathewmariani.com"
baseurl:

plugins:
  - kramdown
  - rouge
  - jekyll-sitemap

permalink: pretty

exclude:
  - "node_modules"
  - "gulpfile.js"
  - "package.json"

# metadata
meta:
  author: "Mathew Mariani"
  title: "Mathew Mariani"
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
  generator: "Jekyll"
  type: "website"
  url: "https://mathewmariani.com"
  image: "https://mathewmariani.com/assets/img/mariani_mat.jpg"
  keywords: "mathew mariani"

# info
info:
  name: "Mathew Mariani"
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
  location: "Montreal, Canada"

social:
  github: https://github.com/mathewmariani
  twitter: https://twitter.com/mattymariani
  email: mailto:mat.mariani@hotmail.com

games:
  name: "Games"
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

programming:
  name: "Programming"
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

graphics:
  name: "Graphics"
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

extensions:
  name: "Extensions"
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

blog:
  name: "Posts"
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
