markdown: kramdown
highlighter: none

url: "https://mathewmariani.com"
baseurl:

plugins:
  - kramdown
  - jekyll-sitemap

permalink: pretty

# disable highlighting
kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
  - "node_modules"
  - "gulpfile.js"
  - "package.json"
  - "vendor"

# metadata
meta:
  author: "Mathew Mariani"
  title: "Mathew Mariani"
  desc: "I am a software developer who enjoys programming end-user software; working on solving new problems, and learning new skills."
  generator: "Jekyll"
  type: "website"
  url: "https://mathewmariani.com"
  image: "https://mathewmariani.com/assets/img/mariani_mat.jpg"
  keywords: "mathew mariani"

# info
info:
  name: "Mathew Mariani"
  location: "Montreal, Canada"
  desc:
    who: "I am a software developer who enjoys programming end-user software; working on solving new problems, and learning new skills."
    what: "I am an open-source contributor and I like making things that help people with their work. I have authored <a href=\"https://mathewmariani.com/marie-simulator/\">MARIE Simulator</a> as a teaching tool for students."
    where: "where"

social:
  github: https://github.com/mathewmariani
  twitter: https://twitter.com/mattymariani
  email: mailto:mat.mariani@hotmail.com

games:
  name: "Games"
  desc: "Some games I've made using technologies such as Love2D, and Unity3D."

programming:
  name: "Programming"
  desc: "Small general stuff I've programmed over time."

graphics:
  name: "Graphics"
  desc: "Some graphical programming using Love2d, OpenGL, and Unity3D."

extensions:
  name: "Extensions"
  desc: "Packages for the hackable text editor Atom."

blog:
  name: "Posts"
  desc: "Small posts I've written to help expand my understanding for topics."
