- title: Natural Language Processing
  img:
  description: Automatic language identification using n-gram based models.
  url: https://mathewmariani.com/ngram-nlp/
  date: 2019-04-27
  tag: JavaScript, VueJS

- title: MARIE Simulator
  img:
  description: An assembly languague simulator written in Javascript with AngularJS.
  url: https://mathewmariani.com/marie-simulator/
  date: 2017-02-13
  tag: JavaScript, VueJS